import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FormEvent } from "react";
import { signUpSchema } from "y/types";
import { toast } from "react-hot-toast";
import { api } from "y/utils/api";
import { useRouter } from "next/router";

const Register: NextPage = () => {
    const router = useRouter()
    const { mutateAsync }  = api.user.signup.useMutation({
        onSuccess: (res) => {
            if(res.success) {
                toast.success(res.messages)
                router.push("/")
            }else{
                toast.error(res.messages)
            }
        },
        onError: (err) => {
            toast.error("something wrong!")
        }
    })
  const handleOnSubmit = async (e:FormEvent) => {
    e.preventDefault()
    const userDateObj = Object.fromEntries(new FormData(e.target as HTMLFormElement)) 
    const input = await signUpSchema.safeParseAsync(userDateObj)
    if(!input.success) input.error.errors.map(err => toast.error(err.message))
    else {
         await mutateAsync(input.data)
    }
  }
  return (
    <>
      <Head>
        <title>Quote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="bg-white font-family-karla h-screen"> 
      <div className="h-full w-full flex flex-wrap">
        <div className="w-full md:w-2/3 flex flex-col m-auto">
            <div className="flex justify-center md:justify-start pt-12 md:pl-12 md:-mb-24">
                <a href="#" className="bg-black text-white font-bold text-xl p-4 mb-3">Register</a>
            </div>
            <div className="flex flex-col w-5/6 m-auto justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p className="text-center text-3xl">Register.</p>
                <form className="flex  flex-col pt-3 md:pt-8" onSubmit={handleOnSubmit}>
                    <div className="flex flex-col pt-4">
                        <label htmlFor="username" className="text-lg">UserName</label>
                        <input type="text" name="username" id="email" placeholder="your name" className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"/>
                    </div>
                    <div className="flex flex-col pt-4">
                        <label htmlFor="email" className="text-lg">email</label>
                        <input type="email" name="email" id="email" placeholder="your@email.com" className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"/>
                    </div>
                    <div className="flex flex-col pt-4">
                        <label htmlFor="password" className="text-lg">Password</label>
                        <input type="password" name="password" id="password" placeholder="password" className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"/>
                    </div>
                    <div className="flex flex-col pt-4">
                        <label htmlFor="password" className="text-lg">Password Confirmation</label>
                        <input type="password" name="confirm" id="password" placeholder="password confirmation" className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline"/>
                    </div>
                    <input type="submit" value="Register" className="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8"/>
                </form>
                <div className="text-center pt-12 pb-12">
                    <p>Do have an account? <Link href="/" className="underline font-semibold">login here.</Link></p>
                </div>
            </div>
        </div>
    </div>
    </div>
    </>);
};

export default Register;

